Public Class ItemObjects
    Public ItemName As String
    Public ItemBase As String
    Public ItemQuality As String
    Public RequiredCharacter As String
    Public EtherealItem As Boolean
    Public Sockets As String
    Public RuneWord As String
    Public ThrowDamageMin As String
    Public ThrowDamageMax As String
    Public OneHandDamageMin As String
    Public OneHandDamageMax As String
    Public TwoHandDamageMin As String
    Public TwoHandDamageMax As String
    Public Defense As String
    Public ChanceToBlock As String
    Public QuantityMin As String
    Public QuantityMax As String
    Public DurabilityMin As String
    Public DurabilityMax As String
    Public RequiredStrength As String
    Public RequiredDexterity As String
    Public RequiredLevel As String
    Public AttackClass As String
    Public AttackSpeed As String
    Public Stat1 As String
    Public Stat2 As String
    Public Stat3 As String
    Public Stat4 As String
    Public Stat5 As String
    Public Stat6 As String
    Public Stat7 As String
    Public Stat8 As String
    Public Stat9 As String
    Public Stat10 As String
    Public Stat11 As String
    Public Stat12 As String
    Public Stat13 As String
    Public Stat14 As String
    Public Stat15 As String
    Public MuleName As String
    Public MuleAccount As String
    Public MulePass As String
    Public PickitBot As String
    Public UserReference As String
    Public ItemImage As String

End Class